# This is an example .goreleaser.yaml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

version: 2  # 添加此行，指定版本

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go generate ./...
    # you may remove this if you don't need go generate

builds:
#  - id: nowin
#    env:
#      - CGO_ENABLED=0
#      - GO111MODULE=on
#    goos:
#      - linux
#      - darwin
#    goarch:
#      - '386'
#      - amd64
#      - arm
#      - arm64
#    goarm:
#      - 7
#    ignore:
#      - goos: darwin
#        goarch: arm
#      - goos: darwin
#        goarch: 386

  - id: win
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7

archives:
  - id: foo
#    builds: [ nowin, win ]
    builds: [ win ]
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
#      - goos: linux
#        format: tar.gz
#      - goos: darwin
#        format: tar.gz