name: Release

on:
  pull_request:
    branches-ignore:
      - "dev"
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      #- name: Checkout Dist
      #  uses: actions/checkout@v2
      #  with:
      #    repository: 'gocq/dist'
      #    ref: master
      #    ssh-key: ${{ secrets.SSH_KEY }}
      #    path: upstream/dist

      #- name: Update Dist
      #  run: |
      #    chmod +x scripts/upload_dist.sh
      #    ./scripts/upload_dist.sh